### ISSUE TITLE
Exception raised at init operating when logged as a superuser

### ISSUE THREAD

**Issue by RUAN0007** [orpheus-db/implementation#4]
If i am logged as a PostgreSQL super user and perform the example init operation, the following exception happens: 
```
machine@machine-HP-Pavilion-15-Notebook-PC:~/Desktop/implementation$ orpheus init test/data.csv dataset -s test/sample_schema.csv

Connecting to the database [machine_db] ...
Creating the dataset [dataset] to the database [machine_db] ...
Creating the data table using the schema provided ...
Creating the version table ...
Creating the index table ...
Initializing the version table ...
Initializing the index table ...
Traceback (most recent call last):
  File "/home/machine/.local/bin/orpheus", line 9, in <module>
    load_entry_point('orpheus==1.0.2', 'console_scripts', 'orpheus')()
  File "/home/machine/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/machine/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/machine/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/machine/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/machine/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/machine/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/machine/.local/lib/python2.7/site-packages/orpheus/clt/click_entry.py", line 128, in init
    executor.exec_init(input_file, dataset, table_name, schema, conn)
  File "/home/machine/.local/lib/python2.7/site-packages/orpheus/core/executor.py", line 76, in exec_init
    raise Exception
Exception
```

However, it seems this dataset is successfully created based on the following list command. 
```
machine@machine-HP-Pavilion-15-Notebook-PC:~/Desktop/implementation$ orpheus ls
Connecting to the database [machine_db] ...
The current database contains the following CVDs:

dataset
```

**Comment by adityagp** [comment]
Thanks for this and your other issue! We'll look into it. @liqixu @SixPlusZero
